### ISSUE TITLE
Scrollbars are not hidden in Firefox on Windows

### ISSUE THREAD

**Issue by skyfrk** [PaloAltoNetworks/docusaurus-openapi-docs#272]
## Describe the bug

In Firefox some scrollbars are rendered that probably should not be rendered (see screenshots below).

### Firefox

![image](https://user-images.githubusercontent.com/27026029/191290338-982c5d80-2735-489f-9223-9df42a87784d.png)
![image](https://user-images.githubusercontent.com/27026029/191290444-f6dd1f94-6749-485b-9172-041249da60cb.png)
![image](https://user-images.githubusercontent.com/27026029/191290493-5e6b86a5-10c4-4468-bf16-579d995775e1.png)
![image](https://user-images.githubusercontent.com/27026029/191290621-3040e34c-a8ea-40e9-8371-696f9b3277e6.png)

### Chrome

![image](https://user-images.githubusercontent.com/27026029/191291694-f24830b4-d484-4b52-86b8-fff870cff643.png)

## Your Environment

- Version used: v1.1.12
- Environment name and version: Firefox 104.0.2 (64-bit)
- Operating System and version (desktop or mobile): Windows 10

**Comment by sserrata** [comment]
I am not able to reproduce on same version of Firefox. Any chance your scroll bars are set to always be visible?

https://support.mozilla.org/en-US/questions/979836#:~:text=You%20can%20make%20the%20scroll,Scroll%20Bar%20%3E%20Choose%20%22Always%22

**Comment by skyfrk** [comment]
I did not find any setting on my system (Windows, not MacOS like in the link you posted) that forces scrollbars to always appear.
Upgrading to the latest Firefox version (105.0) also did not change anything.

@FelixBurkhardAIT I think you were also able to reproduce this issue, correct? Maybe you can share your setup.

**Comment by sserrata** [comment]
Hi @skyfrk, I tested on a Mac so it would it appear to be OS-specific. Have you ruled out any possible accessibility setting in Windows?

(I'll try to spin up a Windows VM today to try to reproduce)

**Comment by FelixBurkhardAIT** [comment]
The problem I experience is a bit differet than described. Firefox shows scrollbars for scrollable elements that occlude parts of the content:
While hovering the cursor over it:
![image](https://user-images.githubusercontent.com/59647538/191531910-957453df-896a-407b-aca5-f26ab9289497.png)
When removing the cursor the scrollbar slowly fades away from this:
![image](https://user-images.githubusercontent.com/59647538/191532337-cb47f446-998f-4f81-b846-8e5a78c4730d.png)
until the scrollbar is complete removed:
![image](https://user-images.githubusercontent.com/59647538/191532277-af082530-8723-4274-848a-eda001278b97.png)
I am using Firefox 105.0 (64-bit) on Windows 11 Enterprise Build 22000.978

**Comment by sserrata** [comment]
Any updates to share? I am hoping to have time to reproduce this week.

**Comment by skyfrk** [comment]
@FelixBurkhardAIT could and I just could do so as well on my other Windows 10 desktop PC.  I also suspect that this is Windows specific.

**Comment by sserrata** [comment]
@skyfrk I was finally able to reproduce something similar on Windows 11 but it's not identical to the issue you reported:


https://user-images.githubusercontent.com/9343811/195428553-c48796c9-e7b8-4e1e-80ef-3185273aad7c.mov

Basically, what I am seeing is that the scrollbar completely covers the content while scrolling. Produced this behavior on Firefox on Windows 11 and Mac.

**Comment by benlei** [comment]
@sserrata I'm observing the same issue on Windows using Firefox.

At the cost of sounding potentially dumb, would it potentially make sense to add `scrollbar-width: none` around https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/1f6bfe79976c07f9b204bd584ea72e8705e4af9e/packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/styles.module.css#L49?

Maybe relevant bugzilla thread: https://bugzilla.mozilla.org/show_bug.cgi?id=1460109#c12

**Comment by sserrata** [comment]
Hi @benlei, thanks for the suggestion. It's been tough to reproduce this particular issue, hence why we haven't been able to address it yet. Can you try applying `scrollbar-width: none` in inspect mode to see if it solves the issue?

**Comment by benlei** [comment]
> Hi @benlei, thanks for the suggestion. It's been tough to reproduce this particular issue, hence why we haven't been able to address it yet. Can you try applying `scrollbar-width: none` in inspect mode to see if it solves the issue?

@sserrata I was able to apply that to an element (body) in my developer console and it hid it, yes. I'm not sure if there are other things to test around it, though. There doesn't seem to be drag scrolling with or without it on Desktop. I was able to press the `<` and `>` icons to see the rest of the options.

**Comment by benlei** [comment]
Here are some pictures:

![image](https://user-images.githubusercontent.com/9943953/218928238-bfccd9f8-0c91-42d0-a1b0-27180b8b379d.png)

Adding in the `scrollbar-width:none` property to response:
![image](https://user-images.githubusercontent.com/9943953/218928399-ca731f7f-51c4-41ee-af85-eacaff073703.png)


Adding in the `scrollbar-width:none` property to response body:

**Comment by sserrata** [comment]
@blindaa121 any thoughts on using `scrollbar-width: none`?

**Comment by blindaa121** [comment]
@sserrata I think `scrollbar-width: none` works fine 👍

**Comment by benlei** [comment]
@sserrata Any update for this?

**Comment by IanVS** [comment]
I can reproduce this on a mac in firefox, and `scrollbar-width: none` seems to do the trick.

**Comment by sserrata** [comment]
This should be addressed in v2.0.0-beta.1 but would appreciate if someone could help test. Thanks!

**Comment by benlei** [comment]
@sserrata It is not fixed in the preview (https://docusaurus-openapi-36b86--pr439-0r874qft.web.app/petstore/place-order/)

![image](https://user-images.githubusercontent.com/9943953/225526934-4d0ed3cc-4453-4437-b76b-1a0eccbe2a2f.png)


------

Once again if I use the browser dev console to add in `scrollbar-width: none` it resolves the issue:

![image](https://user-images.githubusercontent.com/9943953/225527048-a7d9fbfa-abd3-47f8-9ae5-3e6563cf8a70.png)

**Comment by benlei** [comment]
@sserrata Any update for this?

**Comment by Gijsdeman** [comment]
I am experiencing an issue which I think is related to this one. In Firefox for ubuntu, when you scroll in the language tabs, you can scroll in the `codeBlockTitle`, but you are also able to scroll in `codeBlockLines`, which causes different behaviour depending what container you are focused on, as well as a double scroll bar (which I can sadly not capture in my screenshots). However, I do not experience this effect on any of the other components, nor are any other scrollbars visible which should not be.

This is the normal setting, where you are at the top of the code and the title is visible.
![image](https://user-images.githubusercontent.com/43375368/232011992-425d1bbc-c9f9-44c4-a7a1-24ffd6ec9f14.png)

Then, you can scroll while focused on `codeBlockTitle`, making the title disappear.
![image](https://user-images.githubusercontent.com/43375368/232012221-d8b527c1-6ae9-4989-9301-a420d447c762.png)

But you can also scroll while focused on `codeBlockLines`, which has the (intended?) effect of actually scrolling through the code.
![image](https://user-images.githubusercontent.com/43375368/232012286-e1b91422-5cf5-4d93-8416-b3330bb7e7ce.png)

**Comment by matteocontrini** [comment]
This also occurs on Firefox on Mac, I think when an external mouse is connected. Still present on v3.0.0 beta.

**Comment by sserrata** [comment]
@blindaa121, any idea if has been addressed or if it's still an issue?

**Comment by blindaa121** [comment]
@sserrata Ah still looks reproducible on my end, I'll put up the PR for the fix. 👍

**Comment by blindaa121** [comment]
Issue has been resolved in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/785
