### ISSUE TITLE
Uncaught runtime errors: Hook useDoc is called outside the <DocProvider>. 

### ISSUE THREAD

**Issue by guptaashwanee** [PaloAltoNetworks/docusaurus-openapi-docs#637]
Uncaught runtime errors:

ERROR
Hook useDoc is called outside the <DocProvider>. 
ReactContextError
    at useDoc (webpack-internal:///./node_modules/@docusaurus/preset-classic/node_modules/@docusaurus/theme-common/lib/contexts/doc.js:29:112)
    at DocItemMetadata (webpack-internal:///./node_modules/@docusaurus/preset-classic/node_modules/@docusaurus/theme-classic/lib/theme/DocItem/Metadata/index.js:14:139)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16306:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20070:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21583:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4165:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4214:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4278:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27447:7)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26553:12)

My package.json dependencies are:

"dependencies": {
    "@docusaurus/core": "^2.4.3",
    "@docusaurus/plugin-content-docs": "^2.4.3",
    "@docusaurus/preset-classic": "^2.4.3",
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.2.1",
    "docusaurus-plugin-openapi-docs": "^2.0.0-beta.4",
    "docusaurus-plugin-sass": "^0.2.5",
    "docusaurus-theme-openapi-docs": "^2.0.0-beta.4",
    "prism-react-renderer": "^1.3.5",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-lottie": "^1.2.3"
  },

**Comment by sebastian-schuler** [comment]
I'm having the same issue

**Comment by scraymondjr** [comment]
Also having this issue
```
  "dependencies": {
    "@docusaurus/core": "2.4.3",
    "@docusaurus/preset-classic": "2.4.3",
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.2.1",
    "docusaurus-plugin-openapi-docs": "^v1.7.2",
    "docusaurus-theme-openapi-docs": "^v1.7.2",
    "prism-react-renderer": "^1.3.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
```

**Comment by sserrata** [comment]
Hi everyone, Docusaurus introduced some breaking changes to our plugin in `2.4.1`. For now, please stick to `2.4.0`.

**Comment by omonk** [comment]
Hi @sserrata - this is still happening with yesterdays latest release v3.0.1 and a fresh install of docusaurus latest version.

Are they any plans to fix it?

**Comment by Leonzon95** [comment]
I had the same issue. I downloaded the latest of both packages `docusaurus-theme-openapi-docs` & `docusaurus-plugin-openapi-docs`.
```
"docusaurus-plugin-openapi-docs": "^3.0.1",
"docusaurus-theme-openapi-docs": "^2.2.1",
```
For some reason the latest for `docusaurus-theme-openapi-docs` is `2.2.1`. I upgraded that to `3.0.1` and it worked
```
"docusaurus-plugin-openapi-docs": "^3.0.1",
"docusaurus-theme-openapi-docs": "^3.0.1",
```

**Comment by SheedGuy** [comment]
@Leonzon95 doing that fixed it for me too. Not sure why but running:
`yarn upgrade docusaurus-theme-openapi-docs@latest`
installs v2.2.1 like you said. Not sure if its important but I also cleaned (removed) all openAPI docs before upgrading, and then regenerated them afterward.
`yarn clean-api-docs all
# change docusaurus-theme-openapi-docs version in package.json
yarn install
yarn gen-api-docs all
yarn start`

**Comment by sserrata** [comment]
It was a situation where v2.2.1 was released after 3.0.1, which resulted in v2.2.1 getting tagged as "latest". I manually tagged 3.0.1 as latest for `docusaurus-plugin-openapi-docs` but forgot to do the same for the theme. Should be fixed now.

**Comment by Snailmar** [comment]
I also met the same problem, but now, I changed the node version to 20 and pnpm version to 9.6.0.
Then, it works

**Comment by levelMalakhovSergey** [comment]
> Sorry to resurrect an old issue. I'm getting this straight out the box on a new setup following the README.
> 
> Node: `22.11`
> 
> ```
> "dependencies": {
>     "@docusaurus/core": "3.6.3",
>     "@docusaurus/preset-classic": "3.6.3",
>     "@mdx-js/react": "^3.0.0",
>     "clsx": "^2.0.0",
>     "docusaurus-plugin-openapi-docs": "4.3.1",
>     "docusaurus-theme-openapi-docs": "4.3.1",
>     "prism-react-renderer": "^2.3.0",
>     "react": "^18.0.0",
>     "react-dom": "^18.0.0"
>   },
> ```
> 
> I've run: `npx create-docusaurus@3.6.3 developer-docs` Used the template`https://github.com/PaloAltoNetworks/docusaurus-template-openapi-docs.git` Selected "copy" method. Then run `npm start`
> 
> The "Tutorial" and "Petstore API" pages result in the error `Hook useDoc is called outside the <DocProvider>.`
> 
> ```
> Hook useDoc is called outside the <DocProvider>. 
> ReactContextError
>     at useDoc (webpack-internal:///./node_modules/@docusaurus/theme-classic/node_modules/@docusaurus/plugin-content-docs/lib/client/doc.js:30:112)
>     at DocItemMetadata (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocItem/Metadata/index.js:15:144)
>     at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15487:18)
>     at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20099:13)
>     at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21622:16)
>     at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4165:14)
>     at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4214:16)
>     at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4278:31)
>     at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27486:7)
>     at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26592:12)
> ```
> 
> ![Image](https://github.com/user-attachments/assets/4db8e78b-43dc-402f-ac78-5eba62a22acc)

**Comment by levelMalakhovSergey** [comment]
Got simular problem. Just updated node and npm to latest version but still have this error. In my case i forked [docusaurus-openapi-docs](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs) project and tryed to do something like this in my private project. 
` "dependencies": {
    "@docusaurus/core": "^3.5.2",
    "@docusaurus/preset-classic": "^3.5.2",
    "@mdx-js/react": "^3.0.0",
    "clsx": "^2.0.0",
    "docusaurus-plugin-openapi-docs": "file:D:/docus-openapi-v2/docusaurus-openapi-docs/packages/docusaurus-plugin-openapi-docs",
    "docusaurus-theme-openapi-docs": "file:D:/docus-openapi-v2/docusaurus-openapi-docs/packages/docusaurus-theme-openapi-docs" ,
    "prism-react-renderer": "^2.3.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },`
And it send me an error "Hook useDoc is called outside the <DocProvider>.". I didn't modify anything

**Comment by sserrata** [comment]
This error points to a mismatch between docusaurus dependencies. It's not just the explicit ones defined in your package.json, Docusaurus also installs implicit dependencies which could resolve to a different release. I advise thoroughly scrubbing your lock file to try to find/identify possible mismatches between docusaurus deps and employ either resolutions or more explicit dependencies to help prevent the mismatch.

Regarding the template, remember that Docusaurus has released 3.7.0, which means that some implicit deps may resolve to 3.7.0 which would not match the explicit 3.6.3 deps in the template. I'm hoping to update the template and README by end of week to help prevent this from occurring.

**Comment by sserrata** [comment]
Another thing...

As maintainers of this plugin/theme, we cannot control for breaking changes introduced by Docusaurus (which seems to occur with nearly every release). Although we do our best to inform and prevent such issues from occurring, ultimately it boils down to:

* Docusaurus often strictly requires all explicit/implicit deps to be on the exact same release
* Our plugin Docusaurus deps are intentionally defined as a range to try to support as many Docusaurus releases as possible. This is what leaves room for implicit deps to resolve to a mismatched version.
* As users/consumers of Docusaurus and our plugin/theme, it is ultimately your responsibility to ensure all Docusaurus deps are aligned.

**Comment by raldred** [comment]
Absolutely, sounds like managing is a nightmare, no criticism from me, just wanted to try and get up and running.

I've managed to get there for now, by directly cloning the template @ commit [29695b4a4ffbffb7fe19ef2a9fb8f81eed3f092c](https://github.com/PaloAltoNetworks/docusaurus-template-openapi-docs/commit/29695b4a4ffbffb7fe19ef2a9fb8f81eed3f092c)

Which uses docusaurus@3.5.2 and this plugin@4.2.0

All seems to be working fine.

**Comment by ybaldus** [comment]
@sserrata I think the latest release 5.1.2 has this error too. The core was not updated from 5.1.1 to 5.1.2. And downgrading to 5.1.1 solves the issue. 

Edit: 5.1.1 seems also to have issues with the sidebar only with 5.1.0 there are no errors.
