### ISSUE TITLE
Ensure Docusaurus v3 (MDX v3) compatibility

### ISSUE THREAD

**Issue by jasikpark** [PaloAltoNetworks/docusaurus-openapi-docs#654]
### Is your feature request related to a problem?

I would like to easily upgrade my Docusaurus site to v3 in the future (https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3) and I'm uncertain whether this plugin supports Docusaurus v3 / MDX v3

### Describe the solution you'd like

Confirmation that the plugin works with the updated framework version

### Additional context

Just trying to open a preemptive issue so testing can be started before full release

**Comment by smeng9** [comment]
Since we are still in v2 beta yet, shall we consider making v2 release https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/439 compatible with docusaurus 3?

**Comment by lucasassisrosa** [comment]
> Since we are still in v2 beta yet, shall we consider making v2 release #439 compatible with docusaurus 3?

Yes please. Our team is testing `docusaurus-openapi-docs` v2 beta with Docusaurus `v2.4.3` and at least the `mdx` files were considered valid when checking against MDX v2 (`npx docusaurus-mdx-checker`). So I assume most breaking changes should be already figured out?

**Comment by rico0610** [comment]
> Since we are still in v2 beta yet, shall we consider making v2 release #439 compatible with docusaurus 3?

Yes.

**Comment by AnaSofia-1294** [comment]
Is this already available? I need to use a plugin that requires docusaurus v3.

**Comment by jy95** [comment]
@jasikpark Well, if you use OpenAPI >= [3.1.0](https://www.openapis.org/blog/2021/02/18/openapi-specification-3-1-released) , you can use [my plugin](https://github.com/jy95/docusaurus-json-schema-plugin) as starting this version, OpenAPI is fully compatible with JSON Schema

**Comment by jasikpark** [comment]
> [my plugin](https://github.com/jy95/docusaurus-json-schema-plugin)

Thank you for the suggestion, but I'm looking to keep the same plugin for the UI and design choices we've made, and because this OpenAPI plugin has purpose built components for showing api definitions. I'm more interested in teaching my users about how to use the API than being specific about the shape of the spec, it's just a nice way to format the documentation.

**Comment by jasikpark** [comment]
>  at least the `mdx` files were considered valid when checking against MDX v2 (`npx docusaurus-mdx-checker`). So I assume most breaking changes should be already figured out?

For me, when running against my definition I get these errors:

```
Error while compiling file docs/api/role-get.api.mdx (Line=37 Column=1)
Details: Expected a closing tag for `<div>` (37:440-37:445) before the end of `paragraph`
---
Error while compiling file docs/api/roles-list.api.mdx (Line=37 Column=1)
Details: Expected a closing tag for `<div>` (37:1035-37:1040) before the end of `paragraph`
---
```

```mdx
<details style={{"marginBottom":"1rem"}} className={"openapi-markdown__details"} data-collapsed={false} open={true}><summary style={{}}><strong>Query Parameters</strong></summary><div><ul><ParamsItem className={"paramsItem"} param={{"name":"includeCounts","in":"query","description":"If true, return count of total records and current page start and count in metadata","required":false,"schema":{"type":"boolean","default":false}}}></ParamsItem><ParamsItem className={"paramsItem"} param={{"name":"cursor","in":"query","description":"Cursor value at which to start the results, provided in `nextCursor` or `prevCursor` of a prior request","example":"bmV4dA.eyJsb2dzLmNyZQ5iIiwiX3ZhbHVlIjo9In19","schema":{"type":"string"}}}></ParamsItem><ParamsItem className={"paramsItem"} param={{"name":"pageSize","in":"query","description":"Number of records to return in each page","required":false,"schema":{"type":"integer","default":25,"maximum":500}}}></ParamsItem></ul></div></details><div><div><ApiTabs><TabItem label={"200"} value={"200"}><div>
```

Not sure exactly what the issue is..

**Comment by jasikpark** [comment]
<img width="786" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/10626596/fe4a8ceb-e79b-4648-935d-272863e83466">
ah, the issue is that markdown surrounded by JSX always generates a paragraph now unless it is inline I believe.

https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#unintended-extra-paragraphs

**Comment by lucasassisrosa** [comment]
> > at least the `mdx` files were considered valid when checking against MDX v2 (`npx docusaurus-mdx-checker`). So I assume most breaking changes should be already figured out?
> 
> For me, when running against my definition I get these errors:
> 
> ```
> Error while compiling file docs/api/role-get.api.mdx (Line=37 Column=1)
> Details: Expected a closing tag for `<div>` (37:440-37:445) before the end of `paragraph`
> ---
> Error while compiling file docs/api/roles-list.api.mdx (Line=37 Column=1)
> Details: Expected a closing tag for `<div>` (37:1035-37:1040) before the end of `paragraph`
> ---
> ```
> 
> ```mdx
> <details style={{"marginBottom":"1rem"}} className={"openapi-markdown__details"} data-collapsed={false} open={true}><summary style={{}}><strong>Query Parameters</strong></summary><div><ul><ParamsItem className={"paramsItem"} param={{"name":"includeCounts","in":"query","description":"If true, return count of total records and current page start and count in metadata","required":false,"schema":{"type":"boolean","default":false}}}></ParamsItem><ParamsItem className={"paramsItem"} param={{"name":"cursor","in":"query","description":"Cursor value at which to start the results, provided in `nextCursor` or `prevCursor` of a prior request","example":"bmV4dA.eyJsb2dzLmNyZQ5iIiwiX3ZhbHVlIjo9In19","schema":{"type":"string"}}}></ParamsItem><ParamsItem className={"paramsItem"} param={{"name":"pageSize","in":"query","description":"Number of records to return in each page","required":false,"schema":{"type":"integer","default":25,"maximum":500}}}></ParamsItem></ul></div></details><div><div><ApiTabs><TabItem label={"200"} value={"200"}><div>
> ```
> 
> Not sure exactly what the issue is..
> 
> https://mdxjs.com/playground/:
> 
> <img alt="image" width="1259" src="https://user-images.githubusercontent.com/10626596/280380765-478f4293-34c8-4705-bb3e-e61ffae0843c.png">

When I ran into that it was due to the lack of new line chars and the presence of non-escaped characters. I did replacements following Docusaurus migration guide: 

- https://docusaurus.io/docs/migration/v3#bad-usage-of--1
- https://mdxjs.com/migrating/v2/#update-mdx-files

**Comment by jcwillox** [comment]
I managed to fix the MDX output with this simple patch, it's very rudimentary but `pnpm dlx docusaurus-mdx-checker` passed on the ~360 MDX files this plugin generates for our API.

```patch
diff --git a/lib/markdown/utils.js b/lib/markdown/utils.js
index 09d5baef75e5f495c19610021771094463e69ce5..19519432acbe3918dc2db90246bf184fee53f2d5 100644
--- a/lib/markdown/utils.js
+++ b/lib/markdown/utils.js
@@ -13,7 +13,7 @@ function create(tag, props) {
     for (const [key, value] of Object.entries(rest)) {
         propString += ` ${key}={${JSON.stringify(value)}}`;
     }
-    return `<${tag}${propString}>${render(children)}</${tag}>`;
+    return `\n<${tag}${propString}>${render(children)}</${tag}>\n`;
 }
 exports.create = create;
 function guard(value, cb) {
```

However, the UI still crashes with `Hook useDoc is called outside the <DocProvider>.` when I add `docItemComponent: "@theme/ApiItem"` to my config. I believe it's due to the breaking changes related to the removal of `docLayoutComponent` option and the docs theme refactoring https://docusaurus.io/docs/migration/v3#docs-theme-refactoring.

**Comment by sserrata** [comment]
Thanks @jcwillox, have you seen the changes proposed in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/648?

**Comment by jcwillox** [comment]
> Thanks @jcwillox, have you seen the changes proposed in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/648? 

Oh look at that, that's very similar to what I did but an even nicer output 👍, should fix the same issue with mdx, I believe the main issue was multiple opening tags on one line.

**Comment by sserrata** [comment]
Anyone have a chance to try `3.0.0-beta.1`?

**Comment by jcwillox** [comment]
I left a comment here https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/660#issuecomment-1817499261, but tldr, everything looks to be working well, except some syntax highlighing

**Comment by Gijsdeman** [comment]
`3.0.0-beta.1` works for me with Docusaurus `3.0.1`, except for the highlighting as @jcwillox noted. For my documentation I also noticed that I had to add `json` and `bash` to `additionalLanguages` to fix the highlighting for these, while this was not needed for previous Docusaurus versions.

With `3.0.0` I get `Hook is called outside the <DocProvider>`. However, I had this issue with previous versions as well and am not quite sure if it is completely related. 

Great work on the quick release!

**Comment by Gijsdeman** [comment]
After some more testing I ran into an issue with path parameters.

Looking at the [Swagger specifications for describing parameters](https://swagger.io/docs/specification/describing-parameters/), each parameter is denoted each denoted with curly braces. In MDX3 these paramters will be considered to be expressions (see the [Docusaurus migration guide](https://docusaurus.io/docs/migration/v3#bad-usage-of-) for this common issue as well).

Thus, for endpoints with path parameters (in this specific case `{type}`), you will get the following error:
![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/43375368/fb078b6e-d572-416d-80f3-c1f86723aa19)

**Comment by sserrata** [comment]
> After some more testing I ran into an issue with path parameters.

I believe this issue was addressed in v2 #663 and will be ported to v3 soon.

**Comment by Gijsdeman** [comment]
After another inspection I noticed that this error occurs because of parameters that are in the description. We use this to, for example, show what endpoints you should use instead of an deprecated endpoint.

I believe this is another issue than is described in #663 (but I might be mistaken). Since the specifications allow you to use curly braces in summaries, descriptions and other places, I think it would be nice if these are escaped by default where possible.

**Comment by kjeom** [comment]
When I was testing with following testcases, got these errors
1. dacusaurus/core:3.0.0 - docusaurus-plugin-openapi-docs:3.0.0-beta.1
2. dacusaurus/core:3.0.0 - docusaurus-plugin-openapi-docs:3.0.0-beta.2
3. dacusaurus/core:3.0.1 - docusaurus-plugin-openapi-docs:3.0.0-beta.1
4. dacusaurus/core:3.0.1 - docusaurus-plugin-openapi-docs:3.0.0-beta.2

```bash
ERROR
could not find react-redux context value; please ensure the component is wrapped in a <Provider>
    at useReduxContext (webpack-internal:///./node_modules/react-redux/es/hooks/useReduxContext.js:31:11)
    at useSelector (webpack-internal:///./node_modules/react-redux/es/hooks/useSelector.js:136:28)
    at MethodEndpoint (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/lib/theme/ApiExplorer/MethodEndpoint/index.js:6:932)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16306:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20070:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21583:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4165:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4214:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4278:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27447:7)
ERROR
Hook useScrollController is called outside the <ScrollControllerProvider>. 
ReactContextError
    at useScrollController (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:27:145)
    at useScrollPositionBlocker (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:45:63)
    at TabList (webpack-internal:///./node_modules/docusaurus-theme-openapi-docs/lib/theme/MimeTabs/index.js:20:339)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16306:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20070:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21583:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4165:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4214:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4278:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27447:7)
```

**Comment by Gijsdeman** [comment]
> 1. dacusaurus/core:3.0.0 - docusaurus-plugin-openapi-docs:3.0.0-beta.1
> 2. dacusaurus/core:3.0.0 - docusaurus-plugin-openapi-docs:3.0.0-beta.2
> 3. dacusaurus/core:3.0.1 - docusaurus-plugin-openapi-docs:3.0.0-beta.1
> 4. dacusaurus/core:3.0.1 - docusaurus-plugin-openapi-docs:3.0.0-beta.2

As far as my testing brought me any difference in version matching between docusaurus and docusaurus-plugin-openapi-docs will cause issues with redux and hooks. I feel like this might be due to slight mismatches in dependencies, comparable to [this issue](https://github.com/facebook/docusaurus/issues/8091#issuecomment-1262508024).

You should be able to use the [v3.0.0-beta.3](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/releases/tag/v3.0.0-beta.3) release in combination with docusaurus 3.0.1. It will not work with docusaurus 3.0.0 or any older versions.

**Comment by Gijsdeman** [comment]
> Yep, you're totally right, adding `json` and `bash` fixed all the highlighting issues, can't believe I didn't think to do that 😄

I think this issue still persists with [v3.0.0-beta.3](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/releases/tag/v3.0.0-beta.3), and is due to some necessary updates in the theme package. I started refactoring this package but this is a somewhat slow process...

**Comment by techwritermat** [comment]
Hello! Adding `docusaurus-theme-openapi-docs@^2.0.2` to my project introduces a dependency to `"@docusaurus/theme-common" ">=2.4.1 <=2.4.3"`. Can we bump this dependency to ^3.0.0?

**Comment by lennessyy** [comment]
@Gijsdeman The regex for matching curly braces would probably need a little tweaking. 

Right now, if there are two pairs of curly braces on a single line, for example:

```
{key, value} {key, value}
```

The regex would match them as a single pair of brackets and only escape the first and the last one.

**Comment by liamhalemccarty** [comment]
I'm stuck. I was getting the same error @lucasassisrosa was getting:

> For me, when running against my definition I get these errors:
> ```
> Error while compiling file docs/api/role-get.api.mdx (Line=37 Column=1)
> Details: Expected a closing tag for `<div>` (37:440-37:445) before the end of `paragraph`
> ---
> Error while compiling file docs/api/roles-list.api.mdx (Line=37 Column=1)
> Details: Expected a closing tag for `<div>` (37:1035-37:1040) before the end of `paragraph`
> ---
> ```

But fortunately his fix worked for me (thanks @lucasassisrosa!):
> When I ran into that it was due to the lack of new line chars and the presence of non-escaped characters. I did replacements following Docusaurus migration guide:
> 
> * https://docusaurus.io/docs/migration/v3#bad-usage-of--1
> * https://mdxjs.com/migrating/v2/#update-mdx-files

_I only did the first of those fixes — I literally just replaced `<` with `/<` — because I'm not sure what the second link means I should do._

But now I'm getting an error I don't know how to fix:
```
ERROR
Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14888:9)
    at createChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15140:7)
    at reconcileChildrenArray (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15405:25)
    at reconcileChildFibers (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15822:16)
    at reconcileChildren (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19163:28)
    at updateHostComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19920:3)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21614:14)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4165:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4214:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4278:31)
```

More specifically, that first part is sometimes `Objects are not valid as a React child (found: object with keys {textAlign, marginBottom})`. So it seems that code like `\<div style={{"textAlign":"left","marginLeft":"1rem"}}>` is now problematic.

Does anyone know how I can fix this?

**Comment by kjeom** [comment]
Is there anyone who have some trouble like the react-redux error?

**Comment by Gijsdeman** [comment]
> The regex would match them as a single pair of brackets and only escape the first and the last one.

Good catch, I did not take greedy matching into account. I also realized I could just escape all curly brackets instead of just the ones that surround text, thus I opted for that approach.

**Comment by Gijsdeman** [comment]
> Is there anyone who have some trouble like the react-redux error?

Have you tried deleting your `yarn.lock` and all node modules and reinstalled everything (with aligned versions of `docusaurus-*-openapi-docs` and `docusaurus`)? I only had this error due to version mismatches, but a fresh install of all packages always fixed the issue for me.

**Comment by kjeom** [comment]
> > Is there anyone who have some trouble like the react-redux error?
> 
> Have you tried deleting your `yarn.lock` and all node modules and reinstalled everything (with aligned versions of `docusaurus-*-openapi-docs` and `docusaurus`)? I only had this error due to version mismatches, but a fresh install of all packages always fixed the issue for me.

Sure, I have deleted and reinstalled all the things with "@docusaurus/core": "3.0.1" and "docusaurus-plugin-openapi-docs": "^3.0.0-beta.3". But it doesn't work with same react-redux error

**Comment by rsmets** [comment]
I am getting the same error as @kjeom 

https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654#issuecomment-1854087759

Running these versions:

```
  "dependencies": {
    "@docusaurus/core": "^2.3.1",
    "@docusaurus/preset-classic": "^2.3.1",
    "@docusaurus/theme-live-codeblock": "2.3.1",
    "@mdx-js/react": "^1.6.21",
    "docusaurus-plugin-openapi-docs": "^2.0.2",
    "docusaurus-theme-openapi-docs": "^2.0.2",
``` 

So does not seem to be only a 3.0.0 issue.

**Comment by justCXQ** [comment]
> 3.0.0-beta.3
It worked for me like this
```
presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          docRootComponent: "@theme/DocRoot",
          docItemComponent: "@theme/ApiItem", // Derived from docusaurus-theme-openapi
        },
        blog: {
          showReadingTime: true,
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],
```

versions:
```
  "@docusaurus/core": "3.0.1",
    "@docusaurus/preset-classic": "3.0.1",
        "docusaurus-plugin-openapi-docs": "3.0.0-beta.3",
    "docusaurus-theme-openapi-docs": "3.0.0-beta.3",
```

**Comment by kjeom** [comment]
I have also checked it working well 
-  "@docusaurus/core": "3.1.0",
-  "@docusaurus/preset-classic": "3.1.0",
-   "docusaurus-plugin-openapi-docs": "3.0.0-beta.4",
-   "docusaurus-theme-openapi-docs": "3.0.0-beta.4",

**Comment by rdluffy** [comment]
Hello i m still facing the issue, with those versions.

**Comment by dakshika** [comment]
I'm also facing same issue as 

`
[Error [ValidationError]: "docLayoutComponent" is not allowed] {
  _original: {
    sidebarPath: '/Users/dj/git/GTN/gtn-portal/sidebars.js',
    editUrl: 'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/',
    docLayoutComponent: '@theme/DocPage',
    docItemComponent: '@theme/ApiItem'
  },
  details: [
    {
      message: '"docLayoutComponent" is not allowed',
      path: [Array],
      type: 'object.unknown',
      context: [Object]
    }
  ]
}
`

**Comment by kjeom** [comment]
> I'm also facing same issue as
> 
> `[Error [ValidationError]: "docLayoutComponent" is not allowed] { _original: { sidebarPath: '/Users/<>/sidebars.js', editUrl: 'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/', docLayoutComponent: '@theme/DocPage', docItemComponent: '@theme/ApiItem' }, details: [ { message: '"docLayoutComponent" is not allowed', path: [Array], type: 'object.unknown', context: [Object] } ] }`

You should refer https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654#issuecomment-1880640360

change the `docLayoutComponent` to `docRootComponent`

**Comment by raikbitters** [comment]
> You should refer [#654 (comment)](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654#issuecomment-1880640360)
> 
> change the `docLayoutComponent` to `docRootComponent`

Unfortunately, It doesn't help:

Module not found: Error: Can't resolve `'@theme/DocPage'` in `'/workspaces/project-name/.docusaurus'`

**Comment by maxweisel** [comment]
> I have also checked it working well
> 
> * "@docusaurus/core": "3.1.0",
> * "@docusaurus/preset-classic": "3.1.0",
> * "docusaurus-plugin-openapi-docs": "3.0.0-beta.4",
> * "docusaurus-theme-openapi-docs": "3.0.0-beta.4",

I'm still hitting the `Cause: Expected a closing tag for '<div>' (31:488-31:544) before the end of 'paragraph'` with these versions using the openapi-docs example with petstore.yaml.

**Comment by dakshika** [comment]
> > I have also checked it working well
> > 
> > * "@docusaurus/core": "3.1.0",
> > * "@docusaurus/preset-classic": "3.1.0",
> > * "docusaurus-plugin-openapi-docs": "3.0.0-beta.4",
> > * "docusaurus-theme-openapi-docs": "3.0.0-beta.4",
> 
> I'm still hitting the `Cause: Expected a closing tag for '<div>' (31:488-31:544) before the end of 'paragraph'` with these versions using the openapi-docs example with petstore.yaml.

Try to cleanup the generated api docs and run. Also check that `"  themes: ["docusaurus-theme-openapi-docs"],
"` is on config.js

**Comment by dakshika** [comment]
> > I'm also facing same issue as
> > `[Error [ValidationError]: "docLayoutComponent" is not allowed] { _original: { sidebarPath: '/Users/<>/sidebars.js', editUrl: 'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/', docLayoutComponent: '@theme/DocPage', docItemComponent: '@theme/ApiItem' }, details: [ { message: '"docLayoutComponent" is not allowed', path: [Array], type: 'object.unknown', context: [Object] } ] }`
> 
> You should refer [#654 (comment)](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654#issuecomment-1880640360)
> 
> change the `docLayoutComponent` to `docRootComponent`

Thank you this is working now

**Comment by raikbitters** [comment]
> > > I'm also facing same issue as
> > > `[Error [ValidationError]: "docLayoutComponent" is not allowed] { _original: { sidebarPath: '/Users/<>/sidebars.js', editUrl: 'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/', docLayoutComponent: '@theme/DocPage', docItemComponent: '@theme/ApiItem' }, details: [ { message: '"docLayoutComponent" is not allowed', path: [Array], type: 'object.unknown', context: [Object] } ] }`
> > 
> > 
> > You should refer [#654 (comment)](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654#issuecomment-1880640360)
> > change the `docLayoutComponent` to `docRootComponent`
> 
> Thank you this is working now

Hello all. With the same deps I got:

```
ERROR
Hook  is called outside the <DocsSidebarProvider>. 
ReactContextError@webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/reactUtils.js:37:83
useDocsSidebar@webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsSidebar.js:21:132
useSidebarBreadcrumbs@webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/docsUtils.js:55:120
DocBreadcrumbs@webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocBreadcrumbs/index.js:28:641
renderWithHooks@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16306:27
mountIndeterminateComponent@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20070:13
beginWork@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21583:16
callCallback@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4165:14
invokeGuardedCallbackDev@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4214:16
invokeGuardedCallback@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4278:31
beginWork$1@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27447:28
performUnitOfWork@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26556:12
workLoopConcurrent@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26539:22
renderRootConcurrent@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26501:7
performConcurrentWorkOnRoot@webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25734:38
workLoop@webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:267:42
flushWork@webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:240:14
performWorkUntilDeadline@webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:534:21
```

**Comment by maxweisel** [comment]
> > > I have also checked it working well
> > > 
> > > * "@docusaurus/core": "3.1.0",
> > > * "@docusaurus/preset-classic": "3.1.0",
> > > * "docusaurus-plugin-openapi-docs": "3.0.0-beta.4",
> > > * "docusaurus-theme-openapi-docs": "3.0.0-beta.4",
> > 
> > 
> > I'm still hitting the `Cause: Expected a closing tag for '<div>' (31:488-31:544) before the end of 'paragraph'` with these versions using the openapi-docs example with petstore.yaml.
> 
> Try to cleanup the generated api docs and run. Also check that `" themes: ["docusaurus-theme-openapi-docs"], "` is on config.js

Is there a recommended way to do that? I can go through and remove the accidental newlines in the generated mdx files manually, but it would take ages on the petstore example to do by hand. I've got `" themes: ["docusaurus-theme-openapi-docs"], "` in my config already.

**Comment by hadar-co** [comment]
> Hello, I am also getting following error, as soon as I click on one of the endpoint displayed in sidebard
> 
> ```
> could not find react-redux context value; please ensure the component is wrapped in a <Provider>
>     at useReduxContext (webpack-internal:///./node_modules/react-redux/es/hooks/useReduxContext.js:31:11)
> ```
> 
> ```
>     "@docusaurus/core": "3.1.1",
>     "@docusaurus/preset-classic": "3.1.1",
>     "docusaurus-plugin-openapi-docs": "3.0.0-beta.5",
>     "docusaurus-theme-openapi-docs": "3.0.0-beta.5",
>     "prism-react-renderer": "^2.3.0",
> ```

same config and same error :(

**Comment by nagi1** [comment]
There's an Open PR #660, What's missing on that PR to be merged and release v3.0?

**Comment by bohyunjung** [comment]
> > > Hello, I am also getting following error, as soon as I click on one of the endpoint displayed in sidebard
> > > ```
> > > could not find react-redux context value; please ensure the component is wrapped in a <Provider>
> > >     at useReduxContext (webpack-internal:///./node_modules/react-redux/es/hooks/useReduxContext.js:31:11)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > >     "@docusaurus/core": "3.1.1",
> > >     "@docusaurus/preset-classic": "3.1.1",
> > >     "docusaurus-plugin-openapi-docs": "3.0.0-beta.5",
> > >     "docusaurus-theme-openapi-docs": "3.0.0-beta.5",
> > >     "prism-react-renderer": "^2.3.0",
> > > ```
> > 
> > 
> > same config and same error :(
> 
> Yes same here

Same, plus "Expected a closing tag for `<div>`" error.

**Comment by kjeom** [comment]
> > > > Hello, I am also getting following error, as soon as I click on one of the endpoint displayed in sidebard
> > > > ```
> > > > could not find react-redux context value; please ensure the component is wrapped in a <Provider>
> > > >     at useReduxContext (webpack-internal:///./node_modules/react-redux/es/hooks/useReduxContext.js:31:11)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > >     "@docusaurus/core": "3.1.1",
> > > >     "@docusaurus/preset-classic": "3.1.1",
> > > >     "docusaurus-plugin-openapi-docs": "3.0.0-beta.5",
> > > >     "docusaurus-theme-openapi-docs": "3.0.0-beta.5",
> > > >     "prism-react-renderer": "^2.3.0",
> > > > ```
> > > 
> > > 
> > > same config and same error :(
> > 
> > 
> > Yes same here
> 
> Same, plus "Expected a closing tag for `<div>`" error.

Hi, have you tried it after deleting .lock and node_module files? I checked it doesn't occur the error with https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654#issuecomment-1888279640

**Comment by bohyunjung** [comment]
@kjeom That worked. Thank you!

That solved the following issues:
* "Expected a closing tag for `<div>`" error https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654#issuecomment-1792904919
* `could not find react-redux context value;` error https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654#issuecomment-1880640360 

More things that helped me to solve other problems:
* https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654#issuecomment-1895970081 for `Hook useDoc is called outside the <DocProvider>` error

**Comment by IanVS** [comment]
I appreciate that everyone's bringing up issues and helping each other here, but I'm very confused as to the state of the plugin currently.  Is it fully compatible with docusaurus v3, or are the approaches here just workarounds until the plugin is updated to work with v3?  @sserrata could you share what you believe to be the current state?  That would really help bring clarity to those of us waiting to update.

**Comment by sserrata** [comment]
Hi everyone, the latest v3 beta is definitely not tested with the latest docusaurus (3.1.1). It's possible a breaking change was introduced in docusaurus, which is quite common for plugins/themes. That said, I would recommend downgrading to either 3.1.0 or 3.0.1. Also, please ensure all docusaurus dependencies are on the same release - this sometimes requires configuring yarn resolutions or manually pinning versions in package.json.

**Comment by IanVS** [comment]
Great, so it sounds like v3 beta is compatible with at least some versions of docusaurus 3.x?  If so, I'd suggest closing out this issue so that people can open separate individual ones if they have problems.

**Comment by mrcljx** [comment]
Had to make these changes to dedupe dependencies:

```
"resolutions": {
        "@docusaurus/core": "3.1.1",
        "@docusaurus/theme-common": "3.1.1",
        "@docusaurus/plugin-content-docs": "3.1.1",
        "@docusaurus/utils": "3.1.1",
        "@docusaurus/utils-validation": "3.1.1",
        "docusaurus-plugin-openapi-docs": "3.0.0-beta.5",
        "react": "18.2.0",
        "react-redux": "7.2.6"
    },
```

After that I don't see major dupes anymore:

```
$ ls node_modules/docusaurus*openapi-docs/node_modules/

node_modules/docusaurus-plugin-openapi-docs/node_modules/:
clsx/     fs-extra/

node_modules/docusaurus-theme-openapi-docs/node_modules/:
@types/                        sass-loader/
clsx/                          unified/
hast-util-from-parse5/         unist-util-is/
hast-util-parse-selector/      unist-util-position/
hast-util-raw/                 unist-util-stringify-position/
hast-util-to-parse5/           unist-util-visit/
hastscript/                    unist-util-visit-parents/
html-void-elements/            vfile/
parse5/                        vfile-location/
prism-react-renderer/          vfile-message/
rehype-raw/
```

Make sure to include these to avoid the Redux Provider error:

```
docRootComponent: "@theme/DocRoot",
docItemComponent: "@theme/ApiItem",
```

After that the only issue remaining seems to be `hr` and `br` in MDX files:

```
# For macOS, on Linux you have to remove ''
find ./docs/api -type f -name "*.mdx" -exec sed -i '' 's/<hr>/<hr\/>/g' '{}' +
find ./docs/api -type f -name "*.mdx" -exec sed -i '' 's/<br>/<br\/>/g' '{}' +
```

**Comment by jasikpark** [comment]
> Great, so it sounds like v3 beta is compatible with at least some versions of docusaurus 3.x?  If so, I'd suggest closing out this issue so that people can open separate individual ones if they have problems.

Closing my issue 👍
